# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangotestapp.utils
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=djangotestapp.utils.get_uuid4_hex, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(db_index=True)),
                ('description', models.TextField(db_index=True)),
                ('description_html', models.TextField(blank=True, null=True)),
                ('data', jsonfield.fields.JSONField(null=True)),
                ('context_url', models.URLField()),
                ('context', jsonfield.fields.JSONField(null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceEdge',
            fields=[
                ('id', models.UUIDField(default=djangotestapp.utils.get_uuid4_hex, editable=False, primary_key=True, serialize=False)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagbrowser.Resource')),
                ('dest', models.ManyToManyField(related_name='edges_in', to='tagbrowser.Resource')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('source', models.ManyToManyField(related_name='edges_out', to='tagbrowser.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceEdgeType',
            fields=[
                ('id', models.UUIDField(default=djangotestapp.utils.get_uuid4_hex, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(db_index=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='resourceedge',
            name='type',
            field=models.ManyToManyField(related_name='edges', to='tagbrowser.ResourceEdgeType'),
        ),
        migrations.AddField(
            model_name='resourceedge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_edges', to=settings.AUTH_USER_MODEL),
        ),
    ]
