# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(db_index=True, max_length=42)),
                ('message', models.TextField(db_index=True, max_length=140)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('starCount', models.IntegerField(default=0)),
            ],
        ),
    ]
