# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='articleBody',
        ),
    ]
