# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20160715_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='starCount',
            new_name='likeCount',
        ),
    ]
