# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20160715_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='articleBody_html',
            field=models.TextField(null=True),
        ),
    ]
