# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_message_articlebody_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='articleBody_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='hashtags',
            field=models.ManyToManyField(to='testapp.Hashtag'),
        ),
    ]
