# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 05:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0005_auto_20160717_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='testapp.Hashtag'),
        ),
    ]
