# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 19:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0006_auto_20160717_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
