# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 19:24
from __future__ import unicode_literals

from django.db import migrations

from django.contrib.auth import get_user_model


def users_to_foreignkey(apps, schema_editor):
    Message = apps.get_model("testapp", "Message")
    User = get_user_model()
    users_lookup = {}
    for message in Message.objects.all():
        if not message.user:
            # message.delete()       # this is all test data
            message.user = 'to'  # this is all test data
        #user = User.objects.get(username=message.user)  # PRF: RAM / queries
        user, created = users_lookup.setdefault(message.user,
                                User.objects.get_or_create(username=message.user))
        if created:
            user.save()
        message.user_link_id = user.pk
        message.save()


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_message_user_link'),
    ]

    operations = [
        migrations.RunPython(users_to_foreignkey)
    ]
