# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_auto_20160725_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
