# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_drop_orig_user_column'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_link',
            new_name='user'
        )
    ]
